/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "twoumwgowoozpejqflub"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR3b3Vtd2dvd29venBlanFmbHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NDY3ODEsImV4cCI6MjA4NDMyMjc4MX0.RR3oBHwCunCrvnx53OupxXBzx1vnyP-hPB-wip7MsOc"